### ISSUE TITLE
API Version stuff

### ISSUE THREAD

**Issue by Diamondman121314** [EvelynSubarrow/Albatross#1]
Not really an issue, but could you add `api-version: 1.13` (or another version) to the plugin.yml? Without it, it causes Bukkit to initialize Legacy Material Support, which of course this plugin has nothing to do with that. It will still allow the plugin to be used pre-1.13 as well. Unless I'm missing something, there should be no problem with adding it that would cause problems on older versions.

**Comment by EvelynSubarrow** [comment]
It shall be done!

**Comment by EvelynSubarrow** [comment]
The changes are made, I'll have to build it and then upload. I think approval may take longer on bukkitdev, but I should also be putting it on spigot, I'll link them once they're up!

**Comment by EvelynSubarrow** [comment]
https://www.spigotmc.org/resources/commandspy.61494/update?update=372758

**Comment by Diamondman121314** [comment]
Aye, thanks!
